<package format="3">
  <name>palletizer_v1_description</name>
  <version>1.0.0</version>
  <description>
    <p>URDF Description package for palletizer_v1_description</p>
    <p>This package contains configuration data, 3D models and launch files
for palletizer_v1_description robot</p>
  </description>
  <author>TODO</author>
  <maintainer email="TODO@email.com" />
  <license>BSD</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>
  <exec_depend>ros2launch</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>joint_state_publisher_gui</exec_depend>
  <!-- Dependencies for odom_tf_corrector.py -->
  <exec_depend>rclpy</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>python3-scipy</exec_depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>