<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
    <name>finalworkv2_pkg</name>
    <version>1.0.0</version>
    <description>DQN Navigation for differential robot using Stage simulator with sklearn</description>
    <maintainer email="hackbrian@example.com">hackbrian</maintainer>
    <license>MIT</license>

    <buildtool_depend>ament_python</buildtool_depend>

    <!-- ROS2 dependencies -->
    <depend>rclpy</depend>
    <depend>sensor_msgs</depend>
    <depend>nav_msgs</depend>
    <depend>geometry_msgs</depend>
    <depend>std_msgs</depend>
    <depend>tf2_ros</depend>
    <depend>tf_transformations</depend>

    <!-- Launch dependencies -->
    <exec_depend>launch</exec_depend>
    <exec_depend>launch_ros</exec_depend>

    <!-- Python dependencies -->
    <exec_depend>python3-numpy</exec_depend>
    <exec_depend>python3-sklearn</exec_depend>

    <test_depend>ament_copyright</test_depend>
    <test_depend>ament_flake8</test_depend>
    <test_depend>ament_pep257</test_depend>
    <test_depend>python3-pytest</test_depend>

    <export>
        <build_type>ament_python</build_type>
    </export>
</package>
